add_newline = true

format = """\
[â•­â•´](238)$env_var$directory$git_branch$git_status$fill$cmd_duration$nodejs
[â•°â”€](238)$character"""

[fill]
symbol = ' '

[character]
success_symbol = "[ï•“](238)"
error_symbol = "[ï•“](238)"

[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold white)'
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the username
[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = true
show_always = false

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
home_symbol = "ğŸ¡ ~"
read_only_style = "190"
read_only = " ğŸ”’ "
format = "at [$path]($style)[$read_only]($read_only_style) "

[git_branch]
symbol = "ğŸ± "
format = "on [$symbol$branch]($style) "
truncation_symbol = "â€¦/"
style = "bold red"

[git_status]
format = '[\($all_status$ahead_behind\)]($style) '
style = "bold green"
conflicted = "ğŸ³"
up_to_date = "âœ… "
untracked = "ğŸš¸ "
ahead = "ğŸ“°${count}"
diverged = "â‡•â‡¡${ahead_count}â‡£${behind_count}"
behind = "ğŸ•³${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ "
staged = '[++\($count\)](green)'
renamed = "ğŸ”§ "
deleted = "ğŸš® "

[docker_context]
format = "via [ïŒˆ $context](bold blue) "

[nodejs]
format = "[ ğŸ¦ $version](bold green) "

[rust]
format = '[ğŸ¦€]($style)'

[cmd_duration]
format = 'â±  [$duration]($style)'
style = 'bold yellow'

[package]
disabled = true